In [2]:
import pandas as pd
import numpy as np

In [132]:
nicknames = pd.read_csv("nicknames.csv", sep=";", encoding="latin-1")

In [133]:
nicknames.to_csv("nicknames_cleaned.csv", index = False)

In [157]:
nicknames = pd.read_csv("nicknames_cleaned.csv")

In [87]:
mvps = pd.read_csv("mvps.csv", sep=";", encoding="latin-1")

In [241]:
player_stats = pd.read_csv("player_mvp_stats.csv", sep=";", encoding ="latin-1")

In [242]:
player_stats["Player"] = player_stats["Player"].replace({"Nikola Joki?": "Nikola Jokic"})

In [89]:
mvps.to_csv("mvps_cleaned.csv", index = False)

In [243]:
player_stats.to_csv("player_mvp_stats_cleaned.csv", index = False)

In [91]:
mvps = pd.read_csv("mvps_cleaned.csv")

In [244]:
player_stats = pd.read_csv("player_mvp_stats_cleaned.csv")

In [245]:
player_stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,0.484,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,0.286,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,0.470,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,0.459,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,0.455,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [94]:
player_stats[player_stats['Player'] == "Kobe Bryant"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
139,Kobe Bryant,SG,21,LAL,66,62,38.2,8.4,17.9,0.468,...,1210,0.002,Los Angeles Lakers,67,15,0.817,0.0,100.8,92.3,8.41
1051,Kobe Bryant,SG,27,LAL,80,80,41.0,12.2,27.2,0.450,...,1250,0.386,Los Angeles Lakers,45,37,0.549,9.0,99.4,96.9,2.53
1065,Kobe Bryant,SG,28,LAL,77,77,40.8,10.6,22.8,0.463,...,1290,0.404,Los Angeles Lakers,42,40,0.512,19.0,103.3,103.4,0.24
1719,Kobe Bryant,SG,30,LAL,82,82,36.1,9.8,20.9,0.467,...,1210,0.577,Los Angeles Lakers,65,17,0.793,0.0,106.9,99.3,7.11
1733,Kobe Bryant,SG,31,LAL,73,73,38.8,9.8,21.5,0.456,...,1230,0.487,Los Angeles Lakers,57,25,0.695,0.0,101.7,97.0,4.78
6715,Kobe Bryant,SG,29,LAL,82,82,38.9,9.5,20.6,0.459,...,1260,0.873,Los Angeles Lakers,57,25,0.695,0.0,108.6,101.3,7.34
6728,Kobe Bryant,SG,32,LAL,82,82,33.9,9.0,20.0,0.451,...,1210,0.354,Los Angeles Lakers,57,25,0.695,0.0,101.5,95.4,6.01
6746,Kobe Bryant,SG,33,LAL,58,58,38.5,9.9,23.0,0.430,...,1210,0.291,Los Angeles Lakers,41,25,0.621,0.0,97.3,95.9,1.96
6929,Kobe Bryant,SG,34,LAL,78,78,38.6,9.5,20.4,0.463,...,1210,0.152,Los Angeles Lakers,45,37,0.549,11.0,102.2,101.0,1.48
7773,Kobe Bryant,SF,37,LAL,66,66,28.2,6.0,16.9,0.358,...,0,0.000,Los Angeles Lakers,17,65,0.207,56.0,97.3,106.9,-8.92
12064,Kobe Bryant,SG,25,LAL,65,64,37.6,7.9,18.1,0.438,...,1230,0.172,Los Angeles Lakers,56,26,0.683,0.0,98.2,94.3,4.35
12076,Kobe Bryant,SG,26,LAL,66,66,40.7,8.7,20.1,0.433,...,0,0.000,Los Angeles Lakers,34,48,0.415,28.0,98.7,101.7,-2.32
12211,Kobe Bryant,SG,22,LAL,68,68,40.9,10.3,22.2,0.464,...,1240,0.009,Los Angeles Lakers,56,26,0.683,0.0,100.6,97.2,3.74
12224,Kobe Bryant,SG,23,LAL,80,80,38.3,9.4,20.0,0.469,...,1260,0.078,Los Angeles Lakers,58,24,0.707,3.0,101.3,94.1,7.15
12239,Kobe Bryant,SG,24,LAL,82,82,41.5,10.6,23.5,0.451,...,1190,0.417,Los Angeles Lakers,50,32,0.610,9.0,100.4,98.0,2.71
12544,Kobe Bryant,SF,18,LAL,71,6,15.5,2.5,5.9,0.417,...,0,0.000,Los Angeles Lakers,56,26,0.683,1.0,100.0,95.7,3.66
12744,Kobe Bryant,SG,36,LAL,35,35,34.5,7.6,20.4,0.373,...,0,0.000,Los Angeles Lakers,21,61,0.256,46.0,98.5,105.3,-6.17
13184,Kobe Bryant,SG,35,LAL,6,6,29.5,5.2,12.2,0.425,...,0,0.000,Los Angeles Lakers,27,55,0.329,30.0,103.0,109.2,-5.33
13444,Kobe Bryant,SF,19,LAL,79,1,26.0,4.9,11.6,0.428,...,0,0.000,Los Angeles Lakers,61,21,0.744,0.0,105.5,97.8,6.88
13937,Kobe Bryant,SG,20,LAL,50,50,37.9,7.2,15.6,0.465,...,0,0.000,Los Angeles Lakers,31,19,0.620,4.0,99.0,96.0,2.68

In [99]:
def get_pos(name):
    stats = player_stats[player_stats['Player'] == name]
    return stats['Pos'].value_counts().index[0]

In [100]:
get_pos("LeBron James")

'SF'

In [101]:
mvps.iloc[293]

Rank                  10
Player     Manu Ginóbili
Age                   30
Tm                   SAS
First                  0
Pts Won                9
Pts Max             1260
Share              0.007
G                     74
MP                  31.1
PTS                 19.5
TRB                  4.8
AST                  4.5
STL                  1.5
BLK                  0.4
FG%                 0.46
3P%                0.401
FT%                 0.86
WS                  11.1
WS/48              0.232
Year                2008
Name: 293, dtype: object

In [103]:
mvps["POS"] = mvps['Player'].apply(get_pos)

In [110]:
mvps["Player"] = mvps["Player"].replace({"Nikola Joki?": "Nikola Jokic"})

In [111]:
mvps

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year,POS
0,1,Michael Jordan,27,CHI,77,891,960,0.928,82,37.0,...,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991,SG
1,2,Magic Johnson,31,LAL,10,497,960,0.518,79,37.1,...,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991,PG
2,3,David Robinson,25,SAS,6,476,960,0.496,82,37.7,...,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991,C
3,4,Charles Barkley,27,PHI,2,222,960,0.231,67,37.3,...,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991,PF
4,5,Karl Malone,27,UTA,0,142,960,0.148,82,40.3,...,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991,PF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,11,Russell Westbrook,32,WAS,0,5,1010,0.005,65,36.4,...,11.7,1.4,0.4,0.439,0.315,0.656,3.7,0.075,2021,PG
470,12,Ben Simmons,24,PHI,0,3,1010,0.003,58,32.4,...,6.9,1.6,0.6,0.557,0.300,0.613,6.0,0.153,2021,PG
471,13T,James Harden,31,TOT,0,1,1010,0.001,44,36.6,...,10.8,1.2,0.8,0.466,0.362,0.861,7.0,0.208,2021,SG
472,13T,LeBron James,36,LAL,0,1,1010,0.001,45,33.4,...,7.8,1.1,0.6,0.513,0.365,0.698,5.6,0.179,2021,SF
473,13T,Kawhi Leonard,29,LAC,0,1,1010,0.001,52,34.1,...,5.2,1.6,0.4,0.512,0.398,0.885,8.8,0.238,2021,SF

In [115]:
mvps.to_csv("mvps_cleaned.csv", index = False)

In [112]:
true_mvps = mvps[mvps['Rank'] == '1']

In [113]:
true_mvps.columns

Index(['Rank', 'Player', 'Age', 'Tm', 'First', 'Pts Won', 'Pts Max', 'Share',
       'G', 'MP', 'PTS', 'TRB', 'AST', 'STL', 'BLK', 'FG%', '3P%', 'FT%', 'WS',
       'WS/48', 'Year', 'POS'],
      dtype='object')

In [114]:
true_mvps.sort_values(by="Share", ascending = False)

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year,POS
401,1,Stephen Curry,27,GSW,131,1310,1310,1.000,79,34.2,...,6.7,2.1,0.2,0.504,0.454,0.908,17.9,0.318,2016,PG
160,1,Shaquille O'Neal,27,LAL,120,1207,1210,0.998,79,40.0,...,3.8,0.5,3.0,0.574,0.000,0.524,18.6,0.283,2000,C
356,1,LeBron James,28,MIA,120,1207,1210,0.998,76,37.9,...,7.3,1.7,0.9,0.565,0.406,0.753,19.3,0.322,2013,SF
224,1,Kevin Garnett,27,MIN,120,1219,1230,0.991,82,39.4,...,5.0,1.5,2.2,0.499,0.256,0.791,18.3,0.272,2004,PF
83,1,Michael Jordan,32,CHI,109,1114,1130,0.986,82,37.7,...,4.3,2.2,0.5,0.495,0.427,0.834,20.4,0.317,1996,SG
372,1,Kevin Durant,25,OKC,119,1232,1250,0.986,81,38.5,...,5.5,1.3,0.7,0.503,0.391,0.873,19.2,0.295,2014,SF
313,1,LeBron James,25,CLE,116,1205,1230,0.980,76,39.0,...,8.6,1.6,1.0,0.503,0.333,0.767,18.5,0.299,2010,SF
328,1,Derrick Rose,22,CHI,113,1182,1210,0.977,81,37.4,...,7.7,1.0,0.6,0.445,0.332,0.858,13.1,0.208,2011,PG
301,1,LeBron James,24,CLE,109,1172,1210,0.969,81,37.7,...,7.2,1.7,1.1,0.489,0.344,0.780,20.3,0.318,2009,SF
459,1,Nikola Jokic,25,DEN,91,971,1010,0.961,72,34.6,...,8.3,1.3,0.7,0.566,0.388,0.868,15.6,0.301,2021,C
422,1,James Harden,28,HOU,86,965,1010,0.955,72,35.4,...,8.8,1.8,0.7,0.449,0.367,0.858,15.4,0.289,2018,SG
447,1,Giannis Antetokounmpo,25,MIL,85,962,1010,0.952,63,30.4,...,5.6,1.0,1.0,0.553,0.304,0.633,11.1,0.279,2020,PF
20,1,Michael Jordan,28,CHI,80,900,960,0.938,80,38.8,...,6.1,2.3,0.9,0.519,0.270,0.832,17.7,0.274,1992,SG
120,1,Michael Jordan,34,CHI,92,1084,1160,0.934,82,38.8,...,3.5,1.7,0.5,0.465,0.238,0.784,15.8,0.238,1998,SG
435,1,Giannis Antetokounmpo,24,MIL,78,941,1010,0.932,72,32.8,...,5.9,1.3,1.5,0.578,0.256,0.729,14.4,0.292,2019,PF
0,1,Michael Jordan,27,CHI,77,891,960,0.928,82,37.0,...,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991,SG
389,1,Stephen Curry,26,GSW,100,1198,1300,0.922,80,32.7,...,7.7,2.0,0.2,0.487,0.443,0.914,15.7,0.288,2015,PG
176,1,Allen Iverson,25,PHI,93,1121,1240,0.904,71,42.0,...,4.6,2.5,0.3,0.420,0.320,0.814,11.8,0.190,2001,SG
341,1,LeBron James,27,MIA,85,1074,1210,0.888,62,37.5,...,6.2,1.9,0.8,0.531,0.362,0.771,14.5,0.298,2012,SF
267,1,Dirk Nowitzki,28,DAL,83,1138,1290,0.882,78,36.2,...,3.4,0.7,0.8,0.502,0.416,0.904,16.3,0.278,2007,PF
51,1,Hakeem Olajuwon,31,HOU,66,889,1010,0.880,80,41.0,...,3.6,1.6,3.7,0.528,0.421,0.716,14.3,0.210,1994,C
411,1,Russell Westbrook,28,OKC,69,888,1010,0.879,81,34.6,...,10.4,1.6,0.4,0.425,0.343,0.845,13.1,0.224,2017,PG
284,1,Kobe Bryant,29,LAL,82,1100,1260,0.873,82,38.9,...,5.4,1.8,0.5,0.459,0.361,0.840,13.8,0.208,2008,SG
68,1,David Robinson,29,SAS,73,901,1050,0.858,81,38.0,...,2.9,1.7,3.2,0.530,0.300,0.774,17.5,0.273,1995,C
100,1,Karl Malone,33,UTA,63,986,1150,0.857,82,36.6,...,4.5,1.4,0.6,0.550,0.000,0.755,16.7,0.268,1997,PF
37,1,Charles Barkley,29,PHO,59,835,980,0.852,76,37.6,...,5.1,1.6,1.0,0.520,0.305,0.765,14.4,0.242,1993,PF
240,1,Steve Nash,30,PHO,65,1066,1270,0.839,75,34.3,...,11.5,1.0,0.1,0.502,0.431,0.887,10.9,0.203,2005,PG
211,1,Tim Duncan,26,SAS,60,962,1190,0.808,81,39.3,...,3.9,0.7,2.9,0.513,0.273,0.710,16.5,0.248,2003,C
193,1,Tim Duncan,25,SAS,57,954,1260,0.757,82,40.6,...,3.7,0.7,2.5,0.508,0.100,0.799,17.8,0.257,2002,C
256,1,Steve Nash,31,PHO,57,924,1250,0.739,79,35.4,...,10.5,0.8,0.2,0.512,0.439,0.921,12.4,0.212,2006,PG
139,1,Karl Malone,35,UTA,44,827,1180,0.701,49,37.4,...,4.1,1.3,0.6,0.493,0.000,0.788,9.6,0.252,1999,PF

In [123]:
top_3 = mvps[(mvps['Rank'] == '1') | (mvps['Rank'] == '2') | (mvps['Rank'] == '3')]

In [127]:
top_3[top_3["POS"] == "SF"]["Rank"].value_counts()

3    8
2    8
1    5
Name: Rank, dtype: int64

In [135]:
mvps["Tm"].unique()

array(['CHI', 'LAL', 'SAS', 'PHI', 'UTA', 'POR', 'PHO', 'ATL', 'BOS',
       'NYK', 'DET', 'WSB', 'HOU', 'GSW', 'CLE', 'LAC', 'IND', 'ORL',
       'SEA', 'TOT', 'DAL', 'MIA', 'SAC', 'CHH', 'MIN', 'WAS', 'TOR',
       'MIL', 'NJN', 'NOH', 'DEN', 'OKC', 'MEM', 'CHA', 'NOP'],
      dtype=object)

In [158]:
def get_city(name):
    words = name.split()
    
    if len(words) == 2:
        return words[0]
    else:
        return words[0] + " " + words[1]

In [159]:
nicknames = nicknames.replace({"New Orleans/Oklahoma City Hornets": "New Orleans Hornets"})

In [160]:
nicknames["city"] = nicknames["Name"].apply(get_city)

In [164]:
nicknames = nicknames.drop(columns="Name")

In [200]:
nicknames = nicknames.replace({"Golden State": "San Francisco", "Indiana": "Indianapolis", "Minnesota": "Minneapolis",
                   "Portland Trail": "Portland", "Utah": "Salt Lake City"})

In [211]:
state_dict = {
    'Atlanta': "GA",'Brooklyn': "NY", 'Boston': "MA", 'Charlotte': "NC", 'Chicago': "IL",
    'Cleveland': "OH", 'Dallas': "TX", 'Denver': "CO", 'Detroit': "MI", 'San Francisco': "CA",
    'Houston': "TX", 'Indianapolis': "IN", 'Los Angeles': "CA", 'Memphis': "TN", 'Miami': "FL",
    'Milwaukee': "WI", 'Minneapolis': "MN", 'New Jersey': "Duplicate", 'New Orleans': "LA", 'New York': "NY",
    'Oklahoma City': "OK", 'Orlando': "FL", 'Philadelphia': "PA", 'Phoenix': "AZ",
    'Portland': "OR", 'Seattle': "WA", 'Sacramento': "CA", 'San Antonio': "TX",
    'Toronto': "Canada", 'Salt Lake City': "UT", 'Vancouver': "Duplicate", 'Washington': "DC"}
def get_state(city):
    return state_dict[city]

In [213]:
nicknames["state_id"] = nicknames["city"].apply(get_state)

In [223]:
nicknames.iloc[35].to_dict()

{'Abbreviation': 'TOR', 'city': 'Toronto', 'state_id': 'Canada'}

In [215]:
cities = pd.read_csv("uscities.csv")

In [216]:
cities = cities[["city", "state_id", "state_name", "lat", "lng"]]

In [217]:
cities["state_id"].unique()

array(['NY', 'CA', 'IL', 'FL', 'TX', 'PA', 'GA', 'DC', 'MA', 'AZ', 'MI',
       'WA', 'MN', 'CO', 'MD', 'NV', 'MO', 'OR', 'PR', 'OH', 'IN', 'NC',
       'VA', 'WI', 'RI', 'UT', 'TN', 'KY', 'LA', 'CT', 'OK', 'HI', 'NE',
       'NM', 'AL', 'SC', 'IA', 'KS', 'AR', 'ID', 'MS', 'NJ', 'AK', 'NH',
       'ME', 'ND', 'WV', 'SD', 'DE', 'MT', 'VT', 'WY'], dtype=object)

In [218]:
cities[cities["state_id"] == "DC"].sort_values(by = "city", ascending = False).head(40)

         city state_id            state_name      lat      lng
8  Washington       DC  District of Columbia  38.9047 -77.0163

In [219]:
cities[cities["city"] == "Toronto"]

          city state_id    state_name      lat      lng
6211   Toronto       OH          Ohio  40.4581 -80.6095
23503  Toronto       SD  South Dakota  44.5724 -96.6414
24788  Toronto       KS        Kansas  37.7986 -95.9497
28163  Toronto       IA          Iowa  41.9030 -90.8629

In [226]:
cities = cities.merge(nicknames, on = ["city", "state_id"])

In [225]:
last_row = {'Abbreviation': 'TOR', 'city': 'Toronto', 'state_id': 'Canada', "state_name": "None", "lat": 43.741667, "lng": -79.373333}

In [231]:
cities = cities.append(last_row, ignore_index=True)

In [233]:
cities = cities.drop_duplicates("city")

In [234]:
cities.to_csv("city_data_cleaned.csv", index = False)

In [235]:
cities

,city,state_id,state_name,lat,lng,Abbreviation
0,New York,NY,New York,40.694300,-73.924900,NYK
1,Los Angeles,CA,California,34.114100,-118.406800,LAC
3,Chicago,IL,Illinois,41.837500,-87.686600,CHI
4,Miami,FL,Florida,25.784000,-80.210100,MIA
5,Dallas,TX,Texas,32.793500,-96.766700,DAL
6,Houston,TX,Texas,29.786000,-95.388500,HOU
7,Philadelphia,PA,Pennsylvania,40.007700,-75.133900,PHI
8,Atlanta,GA,Georgia,33.762800,-84.422000,ATL
9,Washington,DC,District of Columbia,38.904700,-77.016300,WAS
11,Boston,MA,Massachusetts,42.318800,-71.085200,BOS
12,Phoenix,AZ,Arizona,33.572200,-112.089200,PHX
14,Detroit,MI,Michigan,42.383400,-83.102400,DET
15,San Francisco,CA,California,37.755800,-122.444900,GSW
16,Seattle,WA,Washington,47.621100,-122.324400,SEA
17,Minneapolis,MN,Minnesota,44.963500,-93.267800,MIN
18,Brooklyn,NY,New York,40.650100,-73.949600,BRK
20,Denver,CO,Colorado,39.762000,-104.875800,DEN
21,Portland,OR,Oregon,45.537100,-122.650000,POR
22,San Antonio,TX,Texas,29.463200,-98.523800,SAS
23,Sacramento,CA,California,38.567700,-121.468500,SAC
24,Orlando,FL,Florida,28.477300,-81.337000,ORL
25,Cleveland,OH,Ohio,41.476400,-81.680500,CLE
26,Indianapolis,IN,Indiana,39.777100,-86.145800,IND
27,Charlotte,NC,North Carolina,35.208300,-80.830300,CHA
30,Milwaukee,WI,Wisconsin,43.064200,-87.967500,MIL
31,Salt Lake City,UT,Utah,40.777600,-111.931100,UTA
32,Memphis,TN,Tennessee,35.108700,-89.966300,MEM
33,New Orleans,LA,Louisiana,30.068700,-89.928800,NOH
36,Oklahoma City,OK,Oklahoma,35.467600,-97.513600,OKC
37,Toronto,Canada,None,43.741667,-79.373333,TOR